### ISSUE TITLE
how to get the profile.hmm files ?

### ISSUE THREAD

**Issue by zhoudreames** [enigene/HumAS-HMMER#1]
there is need profile.hmm file in your software.but my species is fish,could you tell me how to gain the files? thanks~

**Comment by zhoudreames** [comment]
I have HiFi 、ONT、and Pb data

**Comment by zhoudreames** [comment]
@enigene

**Comment by enigene** [comment]
You need to use `hmmbuild` tool to convert an alignment to HMM. But first you need to prepare an alignment you want to find in the sample. You can use this reference: http://eddylab.org/software/hmmer3/3.1b2/Userguide.pdf
